export enum ActionTypes {
	AUTH_USER = "AUTH_USER",
	AUTH_START = "AUTH_START",
	AUTH_SUCCESS = "AUTH_SUCCESS",
	AUTH_FAIL = "AUTH_FAIL",
	AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT",
	AUTH_LOGOUT = "AUTH_LOGOUT",
	AUTH_CHECK_STATE = "AUTH_CHECK_STATE",
}
