apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: ankitverma0810/employee
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  # path of the pod name
                  fieldPath: metadata.name
            - name: NATS_URL
              # name of the service defined in the nats-depl file
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              # name of the clusterId define in the nats-depl file
              value: talent
            - name: MONGO_URI
              value: 'mongodb://employee-mongo-srv:27017/employee'
              # This name will be set as one of the env variable in the employee container
            - name: JWT_KEY
              valueFrom:
                # name and key which we have defined while creating the secret
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: employee-srv
spec:
  selector:
    app: employee
  type: ClusterIP
  ports: 
    - name: employee
      protocol: TCP
      port: 3000
      targetPort: 3000