apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees-mongo
  template:
    metadata:
      labels:
        app: employees-mongo
    spec:
      containers:
        - name: employees-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: employees-mongo-srv
spec:
  selector:
    app: employees-mongo
  type: ClusterIP
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017